// Common
export const API_REQUEST = 'API_REQUEST';
export const SAVE_SCROLL_POSITION = 'SAVE_SCROLL_POSITION';
export const SET_ACTIVE_APP = 'SET_ACTIVE_APP';
export const SHOW_ERROR_TOAST = 'SHOW_ERROR_TOAST';